<?php

namespace App\Http\Livewire;

use App\Models\Course;
use App\Models\Section;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Livewire\Component;
use App\Services\AzureOpenAIService;

class ChatPlanner extends Component
{
    public $conversation = [];
    public $input = '';
    public $proposedPlan = null;
    public $chatIsActive = true;

    public function mount()
    {
        // Initialize the conversation with a welcome message from the mock service
        $openAIService = new AzureOpenAIService();
        $initialResponse = $openAIService->getCoursePlan($this->conversation);

        $this->conversation[] = [
            'role' => 'assistant',
            'content' => $initialResponse['response']
        ];
    }

    public function sendMessage()
    {
        if (empty($this->input)) {
            return;
        }

        // Add user message to conversation
        $this->conversation[] = ['role' => 'user', 'content' => $this->input];

        // Get response from AI
        $openAIService = new AzureOpenAIService();
        $response = $openAIService->getCoursePlan($this->conversation);

        // Handle the response
        if ($response['status'] === 'plan_ready') {
            $this->proposedPlan = $response['plan'];
            $this->chatIsActive = false; // Stop the chat
        } else {
            // Add AI response to conversation
            $this->conversation[] = ['role' => 'assistant', 'content' => $response['response']];
        }

        // Clear the input field
        $this->input = '';
    }

    public function render()
    {
        return view('livewire.chat-planner');
    }

    public function acceptPlan()
    {
        if (!$this->proposedPlan) {
            return;
        }

        // Get the first course from the plan
        $firstCourseData = $this->proposedPlan['courses'][0];
        $user = Auth::user();

        // Create the course
        $course = Course::create([
            'title' => $firstCourseData['title'],
            'slug' => Str::slug($firstCourseData['title']),
            'user_id' => $user->id,
            'status' => 'private', // Use 'private' or 'draft' status
            'short_description' => 'This course was auto-generated by StudAI Loop.',
            'description' => 'This course was auto-generated by StudAI Loop based on your learning goals.',
        ]);

        // Create the sections (chapters)
        for ($i = 1; $i <= $firstCourseData['chapters']; $i++) {
            Section::create([
                'course_id' => $course->id,
                'user_id' => $user->id,
                'title' => "Chapter {$i}",
            ]);
        }

        // Redirect the user to the new course
        return redirect()->route('course.details', ['slug' => $course->slug]);
    }

    public function requestChanges()
    {
        $this->chatIsActive = true;
        $this->proposedPlan = null;
        $this->conversation[] = [
            'role' => 'assistant',
            'content' => 'Of course. Please let me know what you would like to change about the proposed plan.'
        ];
    }
}
